module.exports = {
  deposit: require("./deposit"),
  get_payment: require("./get-payment"),
  deposit_history: require("./deposit-history"),
  set_pin: require("./set-pin"),
  update_pin: require("./update-pin"),
  withdraw: require("./withdraw"),
  withdrawal_history: require("./withdrawal-history"),
  accept_deal: require("./accept-deal"),
  reject_deal: require("./reject-deal"),
  make_payment: require("./make-payment"),
  confirm_payment: require("./confirm-payment"),
  reject_payment: require("./reject-payment"),
  refund_payment: require("./refund-payment"),
  release_payment: require("./release-payment"),
};
