module.exports = {
  deposit: require("./deposit"),
  get_payment: require("./get-payment"),
  deposit_history: require("./deposit-history"),
  set_pin: require("./set-pin"),
  update_pin: require("./update-pin"),
  withdraw: require("./withdraw"),
  withdrawal_history: require("./withdrawal-history"),
  accept_deal: require("./accept-deal"),
  reject_deal: require("./reject-deal"),
  make_payment: require("./make-payment"),
  confirm_payment: require("./confirm-payment"),
  reject_payment: require("./reject-payment"),
  confirm_refund: require("./confirm-refund"),
  reject_refund: require("./reject-refund"),
  refund_payment: require("./refund-payment"),
  release_payment: require("./release-payment"),
  confirm_release: require("./confirm-release"),
  reject_release: require("./reject-release"),
  dispute_deal: require("./dispute-deal"),
  confirm_dispute: require("./confirm-dispute"),
  reject_dispute: require("./reject-dispute"),
  solve_seller: require("./solve-seller"),
  solve_buyer: require("./solve-buyer"),
};
